spring:
  mvc:
    throwExceptionIfNoHandlerFound: true
  resources:
    add-mappings: false
  application:
    name: cards-service
  session:
    store-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080