version: '3.3'

services:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - discovery

  redis:
    image: "redis:latest"

  discovery:
    image: "consul"
    ports:
      - "8500:8500"
    environment:
      - CONSUL_LOCAL_CONFIG={"log_level":"info"}

  postgres-user-collections:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgres-scores:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  postgres-auth:
    image: "postgres:10"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - redis
      - postgres-auth

  cards_0:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  cards_1:
    build:
      context: ./cards
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery

  user-collections:
    build:
      context: ./user-collections
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-user-collections
      - auth

  scores:
    build:
      context: ./scores
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
      - discovery
      - postgres-scores