spring:
  application:
    name: scores
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false